version: '3.1'

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: msvcproduct
      MYSQL_USER: msvcproduct
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data.xls:/var/lib/mysql-files/data.xls
